In [1]:
import numpy as np

### Задание 1 
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
N = int(input('Введите N: '))
np.arange(0, N)[::-1]

Введите N: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
matrix = np.diag(np.arange(0, N)[::-1])
print(matrix)
print(f'Сумма элементов по диагонали - {sum([(line[i]) for i, line in enumerate(matrix)])}')

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма элементов по диагонали - 45


### Задание 3
Решите систему уравнений:

4x + 2y + z = 4 

x + 3y = 12 

5y + 4z = -3 

In [4]:
from numpy import linalg

left = np.array([
    [4, 2, 1],
    [1, 3, 0],
    [0, 5,4],
])
right = np.array([4, 12, -3])

linalg.solve(left, right)

array([ 0.46666667,  3.84444444, -5.55555556])

### Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

![](user_matrix.JPG)

Матрица в виде numpy array

In [5]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [6]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [7]:
user_stats_length = np.linalg.norm(next_user_stats)

user_matches = {
    i: np.dot(next_user_stats, user_stats) / (user_stats_length * np.linalg.norm(user_stats))
    for i, user_stats in enumerate(users_stats, 1)
}

user_matches

{1: 0.19999999999999996,
 2: 0.8451542547285165,
 3: 0.3999999999999999,
 4: 0.7905694150420948,
 5: 0.3999999999999999,
 6: 0.0,
 7: 0.0,
 8: 0.9486832980505138,
 9: 0.0,
 10: 0.0}

In [8]:
max(user_matches, key=lambda user: user_matches[user])

8

Ответ - пользователь с 8-ым номером наиболее близок с нашим новым пользователем